### ISSUE TITLE
Null Pointer Exception in BinarySearchTree.right(E)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gauravsaxena81/jctree#1]
```
What steps will reproduce the problem?
1. Execute the test code provided below.

What is the expected output? What do you see instead?

I am getting a NPE:
Exception in thread "main" java.lang.NullPointerException
    at com.googlecode.jctree.BinarySearchTree.right(BinarySearchTree.java:615)
    at kiblerdude.practice.BinaryTrees.main(BinaryTrees.java:77)

What version of the product are you using? On what operating system?

2.0.0 on Windows

Please provide any additional information below.

This is a simple test case that will reproduce the NPE:

BinarySearchTree<Integer> tree = new BinarySearchTree<>();
tree.addAll(Arrays.asList(1,2,5,6,7,90, -99, -5));      
Integer right = tree.right(-5);

It looks the the left() method on BinarySearchTree has implemented some 
defensive checks for this, but the right() method does not have the same 
defensive checks.

```

Original issue reported on code.google.com by `kibl...@gmail.com` on 15 Feb 2015 at 5:33

**Comment by gauravsaxena81** [comment]
Good catch. It seems in my test I had test case numbers wrong. Fixed it now.
